"use client";

export const VALID_CONTAINMENT = {
  "EHR": ["COMPOSITION"],
  "COMPOSITION": ["SECTION", "OBSERVATION", "EVALUATION", "INSTRUCTION", "ACTION", "ADMIN_ENTRY", "CLUSTER", "EVENT_CONTEXT"],
  "SECTION": ["SECTION", "OBSERVATION", "EVALUATION", "INSTRUCTION", "ACTION", "ADMIN_ENTRY", "CLUSTER"],
  "OBSERVATION": ["CLUSTER"],
  "EVALUATION": ["CLUSTER"],
  "INSTRUCTION": ["CLUSTER"],
  "ACTION": ["CLUSTER"],
  "ADMIN_ENTRY": ["CLUSTER"],
  "CLUSTER": ["CLUSTER", "ELEMENT"],
  "EVENT_CONTEXT": ["CLUSTER"]
};

export const RM_TYPES = [
  "COMPOSITION", "SECTION", "OBSERVATION", "EVALUATION", "INSTRUCTION", "ACTION", "ADMIN_ENTRY", "CLUSTER", "ELEMENT", "EVENT_CONTEXT"
];

export const RESERVED_WORDS = [
  'SELECT', 'AS', 'FROM', 'CONTAINS', 'WHERE',
  'ORDER', 'BY', 'LIMIT', 'OFFSET', 'DISTINCT',
  'AND', 'OR', 'NOT', 'EXISTS', 'TOP'
];